### ISSUE TITLE
Enable discussions feature

### ISSUE THREAD

**Issue by daveythacher** [pitschu/RP2040matrix-v2#1]
I would like to have a conversation about some of your timing, BCM, etc. However I am not going to waste either of our time with an issue.

**Comment by pitschu** [comment]
Sure, what's your question?

**Comment by daveythacher** [comment]
Here is some of them:
* BCM has issues with high refresh rates.
* 26MHz is not supported by fan out of most panels and LED drivers.
* FreeRTOS may not respond well from XIP.
* You include binaries in your repo.
* Hardware only works in specific configurations.
* 50Hz scan rate is too low, you will not be able to support all 24 bits with 64x64. There is a couple tricks for getting 24 bit significance but you lose the finer details. (I believe you are mixing up frame rate with refresh/scan rate.)
* Contrast limit is fixed in most panels, but multiplexing distorts this. (24 bit on 32 scan is wasteful.)
* To avoid flicker you need high refresh rate. (100 Hz is min in most cases. Anything beyond 3000 is likely overkill.)

**Comment by pitschu** [comment]
Issue closed. Opened a discussion instead.

**Comment by daveythacher** [comment]
Continue here: https://github.com/pitschu/RP2040matrix-v2/discussions/2
